notifications:
  email: false

branches:
  except:
    - master
    - activey
  
env:
  majorversion: 0
  minorversion: 0

language: cpp
compiler: gcc

#matrix:
#  include:
#      - compiler: gcc
#  - os: linux
#    dist: trusty
#    env: DIST=trusty
#  - os: osx
#    osx_image: xcode7.3
        
cache: ccache

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
#- sudo apt-get update -qq

install:
  #- sudo apt-get install -qq g++-4.8
  #- export CXX="g++-4.8"
  - sudo apt-get -qq install g++-6 gcc-6
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
  - if [[ $TRAVIS_OS_NAME == "osx" ]] ; then brew install --force qt@5.7 ; else sudo apt-get install -y libxtst-dev libx11-dev cmake bc qt5-default qttools5-dev qttools5-dev-tools; fi

script:
  - ./configure
  - make -C build
#  - make -C build test

after_success:
  - ./package_deb.sh

deploy:
  provider: releases
  #tag: 4.2.0_$(TRAVIS_BRANCH)_$(TRAVIS_COMMIT)
  api_key:
    secure: NE+og8E6EfTAdKI0/L55VBFtPbb1aWQzZ351Acw1sBLmiIUGCDKz3ryXKAlJEZppDCRphvYxGHaqRDJ9KMCZsZbsFqUitynNaO4Qxm87BLsfc1Ab3VrLiTCIi2OO+zGrxLdGgSmUCokjNGoq8svrMx/iWEfMf3v5mwgvCD9XFc2YMxGSbIVfErfoiKQqsiiq+kr0LZZW8Z2zBaE8T3pjy5lVPnvr5MFOD8Cw1qDAx76aV8BrFpiLefZ4PTo7mZ4JC7tHiaX9SY6pu3lwjjFP9tZtxsqx1AKKPD6rBeGmKvSRXOKBFwsG76x8qxeAIL1NIzLFotqAUx+brEtsq9WFovjmICYglKona2Srk26o3aPsTyGWG3dZUBxbgx/qvCPfKxyHLnSx7VsOx2V406fL4PB3e53TpiHdA4YbajRRMVwY4w8qLIX7ovqh7IDvAMo20y80O5gf9aEJyRnMVZDSHY83ipsxdEcQY8szXG6JoMZFb6XqDx0RvuoaSL5BZmARLt98SYoHK+0laa+GYSixcC2ljyrVaxKceGdggpvzHWM4bI35eT8KLFdECO6DskhXdSAnOlCMEJsWz3iGlInXaIiavk1Irx+wAj+Vf0JWcwjvvFeGdEeiwtvtjZyN0YqrlLug61bnC35YMk8pUJPNKvjufeEtuSReo0LyOGPlrGg=
  file: "build/deb/synergy_${TRAVIS_BRANCH}.deb"
  #package_glob: "deb/synergy.deb"
  skip_cleanup: true
  on:
    tags: true
    #branch: master
